### ISSUE TITLE
Decode EPC sem a necessidade de saber qual o padrão GS1 foi gerado

### ISSUE THREAD

**Issue by gustavosb26** [jlcout/epctagcoder#14]
Olá Coutinho, tudo bem?

Gostaria de verificar a possiblidade de um decoder do EPC, sem precisar saber o padrão da GS1, no qual foi realizado no encoder.

Exemplo: No serviço de ENCODER/DECODER da GS1, só de informar o código do EPC já é retornado o GS1 Key (padrão) e outros dados durante o decoder. https://www.gs1.org/services/epc-encoderdecoder

Gostaria de saber se o epctagcoder já possui essa funcionalidade genérica, sem a necessidade de saber qual parse devo instanciar.

Agradeço! Abraco!

**Comment by jlcout** [comment]
Olá Gustavo,

Não implementei esse método, no entanto é bem simples identificar o padrão e após identificado executar o parse especifico.

String inputBin = Converter.hexToBin(rfidTag);
String headerBin = inputBin.substring(0, 8);

if (headerBin.equals("00111100") {  // CPI

} else if (headerBin.equals("00101100") {  // GDTI 96

}

Nas classes *Header.java você pode encontrar os identificadores de cada padrão.

Espero ter ajudado.
