### ISSUE TITLE
Unable to get indicator digit in company prefix as company prefix is having only 7 digits

### ISSUE THREAD

**Issue by pkpathak2000** [jlcout/epctagcoder#16]
Hi,
Unable to get indicator digit in company prefix as company prefix is having only 7 digits. is there any way to get indicator digit
As per my understanding If we get indicator digit, UPC should be company prefix + indicator digit + Item Reference

**Comment by jlcout** [comment]
Hi,

What is the EPC implementation?
Please describe in more detail, an example would be helpful.

**Comment by pkpathak2000** [comment]
I implemented UPC =  company prefix +  Item Reference + checkDegits but it is not working in all cases, My understanding if company prefix has indicator digit, UPC should be company prefix + indicator digit + Item Reference. For example. I have a sample EPC - 303403332C121B2F276CB8E8  for my unit testing.  based on the formula (UPC =  company prefix +  Item Reference + checkDegits), I get UPC 052427185402 (which is incorrect). correct UPC is 052427018540. The correct UPC can be achieve if I can get indicator digit in company prefix and apply the formula - company prefix + indicator digit + Item Reference

**Comment by jlcout** [comment]
On the website https://www.gs1.org/services/epc-encoderdecoder and I put the hexadecimal 303403332C121B2F276CB8E8 in the RFID Tag EPC Memory Bank Contents field and it seems to have the same result as my implementation.

{
    "epcScheme": "sgtin",
    "applicationIdentifier": "AI 414 + AI 254",
    "tagSize": "96",
    "filterValue": "1",
    "partitionValue": "5",
    "prefixLength": "7",
    "companyPrefix": "0052427",
    "extensionDigit": "0",
    "itemReference": "18540",
    "serial": "202524899560",
    "checkDigit": "2",
    "epcPureIdentityURI": "urn:epc:id:sgtin:0052427.018540.202524899560",
    "epcTagURI": "urn:epc:tag:sgtin-96:1.0052427.018540.202524899560",
    "epcRawURI": "urn:epc:raw:96.x303403332C121B2F276CB8E8",
    "binary": "001100000011010000000011001100110010110000010010000110110010111100100111011011001011100011101000",
    "rfidTag": "303403332C121B2F276CB8E8"
}



![image](https://github.com/user-attachments/assets/4f67900c-c10b-44fd-8d9f-9f5bb4e8c4c5)

**Comment by pkpathak2000** [comment]
Thanks for your quick response, what is the UPC code based on above details?. 
I used the formula for UPC (CompanyPrefix + ItemReference + CheckDigit) it gives UPC- 052427185402 (which looks like incorrect). and expected UPC is 052427018540

**Comment by jlcout** [comment]
Maybe you're wrong, see that the EPC actually consists of (CompanyPrefix + ItemReference + CheckDigit). But, there is Extension Digit in the first position, before CompanyPrefix.

This digit is used to expand the EPC, if you have reached the maximum numerical limit of this implementation.

Below is an example with Extension Digit = 1 (303403332C73C32F276CB8E8)
![image](https://github.com/user-attachments/assets/75e91adc-ccb8-4c97-98ab-758a9b92c7fa)
