### ISSUE TITLE
GIAI implementation

### ISSUE THREAD

**Issue by mrmar096** [jlcout/epctagcoder#4]
Hi,

Congratulations for the library, it's very useful. Actually, I'm trying to implements the GIAI encoding but I haven't found nothing about this in this library but in the README appears.

Can you help me with this?

Thank you so much.

Regards.

**Comment by jlcout** [comment]
Hi, I'm glad you liked it. Yes, I can help you. I implemented the GIAI
encoding and can tonight update the git. What is your name and company?


José Luiz Coutinho

Em seg, 1 de abr de 2019 às 04:04, mrmar096 <notifications@github.com>
escreveu:

**Comment by mrmar096** [comment]
> Hi, I'm glad you liked it. Yes, I can help you. I implemented the GIAI encoding and can tonight update the git. What is your name and company? José Luiz Coutinho Em seg, 1 de abr de 2019 às 04:04, mrmar096 <notifications@github.com> escreveu:
> […](#)

Hi,

My name is Mario and this is for my spanish company: INNOCV Solutions

Perfect, I will be awaiting for code updates.

Thank you so much for your supporting.

Regards.

**Comment by jlcout** [comment]
Hi Mario,

Version 0.0.6 is available with the GRAI and GIAI implementations.

Look at the attachment, examples with the GIAI implementation.
[sampleGIAI.java.txt](https://github.com/jlcout/epctagcoder/files/3031670/sampleGIAI.java.txt)

**Comment by mrmar096** [comment]
> Hi Mario,
> 
> Version 0.0.6 is available with the GRAI and GIAI implementations.
> 
> Look at the attachment, examples with the GIAI implementation.
> [sampleGIAI.java.txt](https://github.com/jlcout/epctagcoder/files/3031670/sampleGIAI.java.txt)

Hi José,

I'm trying the GIAI implementation and it's working perfectly. Thank you very much for your fast support.

Regards.
